#!/usr/bin/env python3
"""Auto-regenerate the 'Feature systems (high-level inventory)' table in Game.md.

Walks scripts/systems/*.gd, scripts/interactables/*.gd, scripts/ai/*.gd
and scripts/missions/*.gd. Extracts the first `##` doc-comment line as
the one-line summary. Replaces the inventory table in Game.md between
two HTML anchor markers; everything else in Game.md stays untouched.

Markers expected in Game.md:
  <!-- BEGIN AUTO-INVENTORY -->
  ... (auto-regenerated)
  <!-- END AUTO-INVENTORY -->

If the markers don't exist, the script prints a recommended insertion
location and exits without writing.

Called by Janitor weekly + on-demand by CEO.
"""

import argparse, re, sys
from pathlib import Path


def extract_summary(gd_file: Path) -> str:
    """First ## comment line in the file, stripped + truncated."""
    try:
        lines = gd_file.read_text().splitlines()
    except UnicodeDecodeError:
        return "(binary or non-UTF-8 file)"
    for line in lines:
        s = line.strip()
        if s.startswith("##"):
            # Strip leading ##s and whitespace
            summary = s.lstrip("#").strip()
            if summary:
                return summary[:120]
    return "(no doc comment)"


def walk(repo_dir: Path) -> dict[str, list[tuple[str, str]]]:
    """Group GD files by their parent directory. Return {dir: [(file, summary)]}."""
    categories = {
        "Systems": "scripts/systems",
        "Interactables": "scripts/interactables",
        "AI": "scripts/ai",
        "Missions": "scripts/missions",
        "Characters": "scripts/characters",
    }
    out = {}
    for label, subpath in categories.items():
        d = repo_dir / subpath
        if not d.exists():
            continue
        files = sorted(d.glob("*.gd"))
        if not files:
            continue
        out[label] = [(f.name, extract_summary(f)) for f in files]
    return out


def render_table(grouped: dict[str, list[tuple[str, str]]]) -> str:
    lines = []
    lines.append("| Category | File | Summary |")
    lines.append("|---|---|---|")
    for cat, entries in grouped.items():
        for name, summary in entries:
            short = summary.split(". ")[0].strip(".")[:90]  # one-sentence cap
            lines.append(f"| {cat} | `{name}` | {short} |")
    return "\n".join(lines)


def replace_section(game_md: Path, new_table: str) -> int:
    text = game_md.read_text()
    pattern = re.compile(
        r"(<!-- BEGIN AUTO-INVENTORY -->\s*\n).*?(\n<!-- END AUTO-INVENTORY -->)",
        re.DOTALL,
    )
    if not pattern.search(text):
        print("ERROR: <!-- BEGIN AUTO-INVENTORY --> ... <!-- END AUTO-INVENTORY --> markers not found in Game.md.",
              file=sys.stderr)
        print("Add this block to Game.md (e.g., just below the 'Controls' section):",
              file=sys.stderr)
        print("", file=sys.stderr)
        print("    <!-- BEGIN AUTO-INVENTORY -->", file=sys.stderr)
        print(f"    {new_table}", file=sys.stderr)
        print("    <!-- END AUTO-INVENTORY -->", file=sys.stderr)
        return 1
    new_block = f"\\1_Auto-generated by `scripts/generate_game_md_inventory.py`. Do not hand-edit between these markers; per-feature blocks below stay manual._\n\n{new_table}\\2"
    new_text = pattern.sub(new_block, text)
    if new_text != text:
        game_md.write_text(new_text)
        print(f"updated {game_md}")
    else:
        print("no changes (table already up-to-date)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo-dir", default=".")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    repo_dir = Path(args.repo_dir).resolve()
    grouped = walk(repo_dir)
    table = render_table(grouped)
    if args.dry_run:
        print(table)
        return 0
    return replace_section(repo_dir / "Game.md", table)


if __name__ == "__main__":
    sys.exit(main())
