#!/usr/bin/env python3
"""Generate markdown release notes from the factory event archive.

Reads `.factory/history/events.jsonl` (+ archived files in
`.factory/history/archive/`) and renders a CEO-readable release notes
markdown for the window between two timestamps.

Used by release-cut.yml: when tagging v0.N, generates notes covering
the period from the previous tag (or repo creation) to now.

Output sections:
  ## Features shipped       (pr.merged events with kind:feature linked issues)
  ## Bugs fixed             (pr.merged with kind:bug linked issues)
  ## New CEO production work added  (issue.opened for for:ceo issues)
  ## Activity volume        (counts of PRs merged, issues closed, agent runs)
  ## Reliability            (workflow failures, status:needs-ceo escalations)

Usage:
  python generate_release_notes.py --since <ISO> --until <ISO> [--repo-dir DIR]
"""

import argparse, json, os, sys
from collections import defaultdict
from pathlib import Path


def load_events(repo_dir: Path, since: str, until: str) -> list[dict]:
    hist = repo_dir / ".factory" / "history"
    events = []
    candidates = [hist / "events.jsonl"]
    archive = hist / "archive"
    if archive.exists():
        candidates += sorted(archive.glob("*.jsonl"))
    for p in candidates:
        if not p.exists(): continue
        for line in p.read_text().splitlines():
            try:
                e = json.loads(line)
                if since <= e.get("timestamp", "") < until:
                    events.append(e)
            except json.JSONDecodeError:
                continue
    return events


def render(events: list[dict], version: str, since: str, until: str) -> str:
    by_type = defaultdict(list)
    for e in events:
        by_type[e["type"]].append(e)

    merged_prs = by_type["pr.merged"]
    closed_issues = by_type["issue.closed"]
    opened_issues = by_type["issue.opened"]
    releases = by_type["release.cut"]
    failures = by_type["workflow.failed"]

    # Classify merged PRs by linked issue's labels — we logged labels at opened/closed time
    issue_labels = {}
    for e in closed_issues + opened_issues:
        n = e["payload"].get("number")
        if n: issue_labels[n] = e["payload"].get("labels", [])

    features = []
    bugs = []
    chores = []
    for pr in merged_prs:
        title = pr["payload"]["title"]
        # Try to extract linked issue # from the PR title (`(#N)` or `issue #N`)
        import re
        m = re.search(r"#(\d+)", title)
        linked_issue = int(m.group(1)) if m else None
        labels = issue_labels.get(linked_issue, [])
        if "kind:bug" in labels:
            bugs.append(pr)
        elif "kind:chore" in labels:
            chores.append(pr)
        else:
            features.append(pr)

    ceo_queue_new = [e for e in opened_issues if "for:ceo" in e["payload"].get("labels", [])]

    out = [
        f"# Release {version}",
        "",
        f"_Window: {since[:16]} → {until[:16]} UTC_",
        "",
    ]

    if features:
        out.append("## ✨ Features shipped")
        out.append("")
        for pr in features:
            num = pr["payload"]["number"]
            out.append(f"- **#{num}** {pr['payload']['title']}")
        out.append("")

    if bugs:
        out.append("## 🐛 Bugs fixed")
        out.append("")
        for pr in bugs:
            num = pr["payload"]["number"]
            out.append(f"- **#{num}** {pr['payload']['title']}")
        out.append("")

    if chores:
        out.append("## 🧹 Chores / infrastructure")
        out.append("")
        for pr in chores:
            num = pr["payload"]["number"]
            out.append(f"- **#{num}** {pr['payload']['title']}")
        out.append("")

    if ceo_queue_new:
        out.append("## 🎨 New CEO production work")
        out.append("")
        for i in ceo_queue_new:
            num = i["payload"]["number"]
            kinds = [l.replace("kind:", "") for l in i["payload"].get("labels", []) if l.startswith("kind:") and l != "kind:feature"]
            kind = f" *({', '.join(kinds)})*" if kinds else ""
            out.append(f"- **#{num}** {i['payload']['title']}{kind}")
        out.append("")

    out.append("## 📊 Activity")
    out.append("")
    out.append(f"- {len(merged_prs)} PRs merged")
    out.append(f"- {len(closed_issues)} issues closed")
    out.append(f"- {len(opened_issues)} new issues filed ({len(ceo_queue_new)} for CEO queue)")
    if failures:
        out.append(f"- {len(failures)} workflow failures during this window")
    out.append("")

    if not (features or bugs or chores):
        out.append("## ⚠️ Note")
        out.append("")
        out.append("No PRs merged in this release window. Tag created for cadence consistency.")
        out.append("")

    out.append("---")
    out.append("")
    out.append("_Generated by `generate_release_notes.py` from `.factory/history/events.jsonl`. Edit this release on GitHub if you want to humanize the prose before announcing._")

    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--since", required=True, help="ISO timestamp, inclusive")
    ap.add_argument("--until", required=True, help="ISO timestamp, exclusive")
    ap.add_argument("--version", required=True, help="release version (e.g. v0.1)")
    ap.add_argument("--repo-dir", default=".", help="repo dir containing .factory/")
    ap.add_argument("--output", help="output file (default: stdout)")
    args = ap.parse_args()

    repo_dir = Path(args.repo_dir).resolve()
    events = load_events(repo_dir, args.since, args.until)
    notes = render(events, args.version, args.since, args.until)
    if args.output:
        Path(args.output).write_text(notes)
        print(f"wrote {args.output} ({len(notes)} chars, {len(events)} events)")
    else:
        print(notes)
    return 0


if __name__ == "__main__":
    sys.exit(main())
